### ISSUE TITLE
not specifying iso_dir in the COMMONS: section

### ISSUE THREAD

**Issue by Pathjana** [Pathangi-Jatinshravan/Network_Topology#4]
If I do not mention the iso_dir in the COMMONS: section, I get the following traceback
Traceback (most recent call last):
  File "./nw_topo.py", line 255, in <module>
    main()
  File "./nw_topo.py", line 111, in main
    data = json.load(f)
  File "/usr/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 7 column 13 (char 130)

the error message must be clearer and indicate that iso_dir is missing in the COMMONS section and needs to be added.

**Comment by Pathjana** [comment]
This is probably a general error checking that has to be added on all the mandatory fields required in the config file. For e.g. if the name of the VM is not present or its version not present etc. would cause similar issues.
 Should look at fixing all mandatory fields checks.
